name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"
      - run: npm install --frozen-lockfile
      - run: npm lint
      - run: npm test
      - run: npm run test:integration
      # make sure the build works
      - run: npm run build:server
      - run: npm run build
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ""
